# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
simple_effort_ctrl: 
 #proportional
 #gains_p: [50, 612.71801, 612.71801, 50, 40, 5]
 gains_p: [5, 61.271801, 61.271801, 5, 4, 0.5]

 gains_p_cart: [100, 100, 100, 10, 10, 10, 10]
 
 #derivative
 gains_d: [100, 75, 75, 73, 15, 5]
 #gains_d: [1000, 750, 750, 730, 150, 50]

 gains_d_cart: [100, 100, 100, 10, 10, 10, 10]

#integral
 gains_i: [0, 0, 0, 0, 0, 0]
 #gains_i: [40, 30, 30, 30, 6, 2]

 gains_i_cart: [0, 0, 0, 0, 0, 0, 0]

 # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
 # goal: [0, -90, 90, -90, 0, 0]
 goal: [0, -90, -90, 0, 90, 0]
 #goal: [20, -100, 70, -165, -80, 15]

 # start_pose: [-0.5, 0.0, 0.7, 0.0, 1.57, 0.0]
 #start_pose: [-0.5, -0.0, 1.0, 1.57, 0.0, 1.57]
 start_pose: [-0.55, 0.5, 1.0, 0.5, 0.5, -0.5, -0.5]
 execution_time: [10.0,5.0]

 gamma: [0.1]
 
 THR_DeltaQ: [0.5]
 THR_DeltaX: [0.05]
 THR_SING: [0.01]
 THR_MANI: [0.1]
