trajectory_generator:
  point_min_x: 1200
  point_max_x: 5000
  point_min_y: 5000
  point_max_y: 1300
  window_min_x: 0.7  #0.68
  window_max_x: -0.5 #-0.68
  window_min_y: 0.3  # 0.3
  window_max_y: 0.9  # 1.3
  window_init_x: 0.5
  window_init_y: 1
  window_min_v: 0.01
  window_max_v: 0.12
  window_max_d: 0.125
  
