trajectory_generator:
  point_min_x: 1500
  point_max_x: 5000
  point_min_y: 1500
  point_max_y: 5000
  window_min_x: -0.5
  window_max_x: 0.5
  window_min_y: -0.5
  window_max_y: 0.5
  window_init_x: 0.0
  window_init_y: 0.0
  window_min_v: 0.01
  window_max_v: 0.1
  window_max_d: 0.1
  
